/*
 * Copyright © 02.10.2015 by O.I.Mudannayake. All Rights Reserved.
 */
package purchaseorder;

import java.awt.event.ActionListener;
import javax.swing.event.InternalFrameListener;
import controller.View;
import java.awt.Color;
import javax.swing.BorderFactory;
import ui.ColourPalatte;

/**
 *
 * @author Ivantha
 */
public class NewPO extends javax.swing.JInternalFrame implements View {

    /**
     * Creates new form NewPOView
     */
    public NewPO() {
        initComponents();

        this.newPOPanel.setBackground(ColourPalatte.MEDIUM_BLUE);
        this.paymentPanel.setBackground(ColourPalatte.MEDIUM_BLUE);

        this.supplierLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.itemListLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.advancePaymentLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.amountLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.bankLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.noLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentMethodButtonGroup = new javax.swing.ButtonGroup();
        newPOPanel = new javax.swing.JPanel();
        supplierLabel = new javax.swing.JLabel();
        supplierNameComboBox = new javax.swing.JComboBox();
        itemListLabel = new javax.swing.JLabel();
        itemListNameComboBox = new javax.swing.JComboBox();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        advancePaymentLabel = new javax.swing.JLabel();
        noneRadioButton = new javax.swing.JRadioButton();
        cashRadioButton = new javax.swing.JRadioButton();
        chequeRadioButton = new javax.swing.JRadioButton();
        debitCardRadioButton = new javax.swing.JRadioButton();
        creditCardRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();
        noTextField = new javax.swing.JTextField();
        noLabel = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        bankTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        printCheckBox = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("New purchase order");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/icon/po_button_dark.png"))); // NOI18N

        supplierLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        supplierLabel.setText("Supplier");

        supplierNameComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        itemListLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        itemListLabel.setText("Item list");

        itemListNameComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        newButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        newButton.setText("New");
        newButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newButtonMouseExited(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        editButton.setText("Edit");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });

        advancePaymentLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        advancePaymentLabel.setText("Advance payment");

        paymentMethodButtonGroup.add(noneRadioButton);
        noneRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        noneRadioButton.setSelected(true);
        noneRadioButton.setText("None");

        paymentMethodButtonGroup.add(cashRadioButton);
        cashRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cashRadioButton.setText("Cash");

        paymentMethodButtonGroup.add(chequeRadioButton);
        chequeRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        chequeRadioButton.setText("Cheque");

        paymentMethodButtonGroup.add(debitCardRadioButton);
        debitCardRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        debitCardRadioButton.setText("Debit card");

        paymentMethodButtonGroup.add(creditCardRadioButton);
        creditCardRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        creditCardRadioButton.setText("Credit card");

        okButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButtonMouseExited(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearButtonMouseExited(evt);
            }
        });

        paymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        noTextField.setText(" ");
        noTextField.setBorder(null);
        paymentPanel.add(noTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, 25));

        noLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        noLabel.setText("No.");
        paymentPanel.add(noLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        bankLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bankLabel.setText("Bank");
        paymentPanel.add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        bankTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bankTextField.setText(" ");
        bankTextField.setBorder(null);
        paymentPanel.add(bankTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, 25));

        amountTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        amountTextField.setText(" ");
        amountTextField.setBorder(null);
        paymentPanel.add(amountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 25));

        amountLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        amountLabel.setText("Amount");
        paymentPanel.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        printCheckBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        printCheckBox.setSelected(true);
        printCheckBox.setText("Print");
        printCheckBox.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout newPOPanelLayout = new javax.swing.GroupLayout(newPOPanel);
        newPOPanel.setLayout(newPOPanelLayout);
        newPOPanelLayout.setHorizontalGroup(
            newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPOPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPOPanelLayout.createSequentialGroup()
                        .addComponent(supplierLabel)
                        .addGap(77, 77, 77)
                        .addComponent(supplierNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(newPOPanelLayout.createSequentialGroup()
                            .addComponent(itemListLabel)
                            .addGap(77, 77, 77)
                            .addComponent(itemListNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newPOPanelLayout.createSequentialGroup()
                            .addComponent(advancePaymentLabel)
                            .addGap(28, 28, 28)
                            .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(newPOPanelLayout.createSequentialGroup()
                                    .addComponent(noneRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(cashRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(chequeRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(debitCardRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(creditCardRadioButton)
                                    .addGap(55, 55, 55))
                                .addGroup(newPOPanelLayout.createSequentialGroup()
                                    .addComponent(printCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(174, 174, 174)
                                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(paymentPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        newPOPanelLayout.setVerticalGroup(
            newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPOPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPOPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(supplierLabel))
                    .addComponent(supplierNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newPOPanelLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(itemListLabel))
                        .addComponent(itemListNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPOPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(advancePaymentLabel))
                    .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(noneRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cashRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chequeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(debitCardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(creditCardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(newPOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newPOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newPOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseEntered
        this.newButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.newButton.setForeground(ColourPalatte.FONT_BLUE);
        this.newButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_newButtonMouseEntered

    private void newButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseExited
        this.newButton.setBackground(ColourPalatte.DARK_BLUE);
        this.newButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.newButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_newButtonMouseExited

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        this.editButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.editButton.setForeground(ColourPalatte.FONT_BLUE);
        this.editButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        this.editButton.setBackground(ColourPalatte.DARK_BLUE);
        this.editButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.editButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_editButtonMouseExited

    private void okButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseEntered
        this.okButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.okButton.setForeground(ColourPalatte.FONT_BLUE);
        this.okButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_okButtonMouseEntered

    private void okButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseExited
        this.okButton.setBackground(ColourPalatte.DARK_BLUE);
        this.okButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.okButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_okButtonMouseExited

    private void clearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseEntered
        this.clearButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.clearButton.setForeground(ColourPalatte.FONT_BLUE);
        this.clearButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_clearButtonMouseEntered

    private void clearButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseExited
        this.clearButton.setBackground(ColourPalatte.DARK_BLUE);
        this.clearButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.clearButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_clearButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advancePaymentLabel;
    javax.swing.JLabel amountLabel;
    javax.swing.JTextField amountTextField;
    javax.swing.JLabel bankLabel;
    javax.swing.JTextField bankTextField;
    javax.swing.JRadioButton cashRadioButton;
    javax.swing.JRadioButton chequeRadioButton;
    private javax.swing.JButton clearButton;
    javax.swing.JRadioButton creditCardRadioButton;
    javax.swing.JRadioButton debitCardRadioButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel itemListLabel;
    javax.swing.JComboBox itemListNameComboBox;
    private javax.swing.JButton newButton;
    private javax.swing.JPanel newPOPanel;
    javax.swing.JLabel noLabel;
    javax.swing.JTextField noTextField;
    javax.swing.JRadioButton noneRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup paymentMethodButtonGroup;
    private javax.swing.JPanel paymentPanel;
    javax.swing.JCheckBox printCheckBox;
    private javax.swing.JLabel supplierLabel;
    javax.swing.JComboBox supplierNameComboBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViewInternalFrameListener(InternalFrameListener ifl) {
        this.addInternalFrameListener(ifl);
    }

    public void addNewButtonActionListener(ActionListener al) {
        newButton.addActionListener(al);
    }

    public void addEditButtonActionListener(ActionListener al) {
        editButton.addActionListener(al);
    }

    public void addOKButtonActionListener(ActionListener al) {
        okButton.addActionListener(al);
    }

    public void addClearButtonActionListener(ActionListener al) {
        clearButton.addActionListener(al);
    }

    public void addNoneRadioButtonActionListener(ActionListener al) {
        noneRadioButton.addActionListener(al);
    }

    public void addCashRadioButtonActionListener(ActionListener al) {
        cashRadioButton.addActionListener(al);
    }

    public void addChequeRadioButtonActionListener(ActionListener al) {
        chequeRadioButton.addActionListener(al);
    }

    public void addDebitCardRadioButtonActionListener(ActionListener al) {
        debitCardRadioButton.addActionListener(al);
    }

    public void addCreditCardRadioButtonActionListener(ActionListener al) {
        creditCardRadioButton.addActionListener(al);
    }
}
