/*
 * Copyright © 02.10.2015 by O.I.Mudannayake. All Rights Reserved.
 */
package invoice;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.event.InternalFrameListener;
import controller.View;
import java.awt.event.KeyListener;
import javax.swing.BorderFactory;
import ui.ColourPalatte;

/**
 *
 * @author Ivantha
 */
public class NewInvoice extends javax.swing.JInternalFrame implements View {

    /**
     * Creates new form NewInvoiceView
     */
    public NewInvoice() {
        initComponents();

        this.newInvoicePanel.setBackground(ColourPalatte.MEDIUM_BLUE);
        this.paymentPanel.setBackground(ColourPalatte.MEDIUM_BLUE);

        this.customerLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.netAmountLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.amountPaidLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.paymentMethodLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.bankLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.noLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.searchLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        
        this.netAmountTextField.setBackground(ColourPalatte.VERY_LIGHT_BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentMethodButtonGroup = new javax.swing.ButtonGroup();
        newInvoicePanel = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemListTable = new javax.swing.JTable();
        netAmountLabel = new javax.swing.JLabel();
        netAmountTextField = new javax.swing.JTextField();
        amountPaidLabel = new javax.swing.JLabel();
        amountPaidTextField = new javax.swing.JTextField();
        paymentMethodLabel = new javax.swing.JLabel();
        cashRadioButton = new javax.swing.JRadioButton();
        chequeRadioButton = new javax.swing.JRadioButton();
        debitCardRadioButton = new javax.swing.JRadioButton();
        creditCardRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemListJList = new javax.swing.JList();
        paymentPanel = new javax.swing.JPanel();
        bankLabel = new javax.swing.JLabel();
        bankTextField = new javax.swing.JTextField();
        noLabel = new javax.swing.JLabel();
        noTextField = new javax.swing.JTextField();
        printCheckBox = new javax.swing.JCheckBox();
        searchTextField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("New invoice");
        setFrameIcon(new javax.swing.ImageIcon(ClassLoader.getSystemClassLoader().getResource("icon/invoice_button_dark.png"))); // NOI18N

        customerLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        customerLabel.setText("Customer");

        customerComboBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        itemListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item no.", "Name", "Qty", "Unit price", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemListTable.setRowHeight(20);
        jScrollPane1.setViewportView(itemListTable);
        if (itemListTable.getColumnModel().getColumnCount() > 0) {
            itemListTable.getColumnModel().getColumn(0).setMinWidth(100);
            itemListTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            itemListTable.getColumnModel().getColumn(0).setMaxWidth(100);
            itemListTable.getColumnModel().getColumn(2).setMinWidth(100);
            itemListTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            itemListTable.getColumnModel().getColumn(2).setMaxWidth(100);
            itemListTable.getColumnModel().getColumn(3).setMinWidth(100);
            itemListTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            itemListTable.getColumnModel().getColumn(3).setMaxWidth(100);
            itemListTable.getColumnModel().getColumn(4).setMinWidth(100);
            itemListTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            itemListTable.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        netAmountLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        netAmountLabel.setText("Net amount");

        netAmountTextField.setEditable(false);
        netAmountTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        netAmountTextField.setText(" ");
        netAmountTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        amountPaidLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        amountPaidLabel.setText("Amount paid");

        amountPaidTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        amountPaidTextField.setText(" ");
        amountPaidTextField.setBorder(null);

        paymentMethodLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        paymentMethodLabel.setText("Payment method");

        paymentMethodButtonGroup.add(cashRadioButton);
        cashRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cashRadioButton.setSelected(true);
        cashRadioButton.setText("Cash");

        paymentMethodButtonGroup.add(chequeRadioButton);
        chequeRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        chequeRadioButton.setText("Cheque");

        paymentMethodButtonGroup.add(debitCardRadioButton);
        debitCardRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        debitCardRadioButton.setText("Debit card");

        paymentMethodButtonGroup.add(creditCardRadioButton);
        creditCardRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        creditCardRadioButton.setText("Credit card");

        okButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButtonMouseExited(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearButtonMouseExited(evt);
            }
        });

        itemListJList.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(itemListJList);

        paymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bankLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bankLabel.setText("Bank");
        paymentPanel.add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 25, -1, -1));

        bankTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bankTextField.setText(" ");
        bankTextField.setBorder(null);
        paymentPanel.add(bankTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 20, 100, 25));

        noLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        noLabel.setText("No.");
        paymentPanel.add(noLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 25, -1, -1));

        noTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        noTextField.setText(" ");
        noTextField.setBorder(null);
        paymentPanel.add(noTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 20, 100, 25));

        printCheckBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        printCheckBox.setText("Print");
        printCheckBox.setPreferredSize(new java.awt.Dimension(80, 25));

        searchTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        searchTextField.setText(" ");
        searchTextField.setBorder(null);

        searchLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        searchLabel.setText("Search");

        javax.swing.GroupLayout newInvoicePanelLayout = new javax.swing.GroupLayout(newInvoicePanel);
        newInvoicePanel.setLayout(newInvoicePanelLayout);
        newInvoicePanelLayout.setHorizontalGroup(
            newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newInvoicePanelLayout.createSequentialGroup()
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentMethodLabel)
                                    .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(cashRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(chequeRadioButton)))
                                .addGap(18, 18, 18)
                                .addComponent(debitCardRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(creditCardRadioButton))
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addComponent(customerLabel)
                                .addGap(61, 61, 61)
                                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                        .addComponent(netAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96)
                                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                                .addGap(115, 115, 115)
                                                .addComponent(amountPaidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(amountPaidLabel)))))
                            .addComponent(netAmountLabel)
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInvoicePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(searchLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInvoicePanelLayout.createSequentialGroup()
                        .addComponent(printCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        newInvoicePanelLayout.setVerticalGroup(
            newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newInvoicePanelLayout.createSequentialGroup()
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerLabel)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 31, Short.MAX_VALUE)
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netAmountLabel)
                            .addComponent(amountPaidLabel)
                            .addComponent(amountPaidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(paymentMethodLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chequeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(debitCardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditCardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newInvoicePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(7, 7, 7)
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchLabel))
                        .addGap(37, 37, 37)))
                .addGap(18, 18, 18)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newInvoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newInvoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseEntered
        this.okButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.okButton.setForeground(ColourPalatte.FONT_BLUE);
        this.okButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_okButtonMouseEntered

    private void okButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseExited
        this.okButton.setBackground(ColourPalatte.DARK_BLUE);
        this.okButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.okButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_okButtonMouseExited

    private void clearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseEntered
        this.clearButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.clearButton.setForeground(ColourPalatte.FONT_BLUE);
        this.clearButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_clearButtonMouseEntered

    private void clearButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseExited
        this.clearButton.setBackground(ColourPalatte.DARK_BLUE);
        this.clearButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.clearButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_clearButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPaidLabel;
    javax.swing.JTextField amountPaidTextField;
    javax.swing.JLabel bankLabel;
    javax.swing.JTextField bankTextField;
    javax.swing.JRadioButton cashRadioButton;
    javax.swing.JRadioButton chequeRadioButton;
    private javax.swing.JButton clearButton;
    javax.swing.JRadioButton creditCardRadioButton;
    javax.swing.JComboBox customerComboBox;
    private javax.swing.JLabel customerLabel;
    javax.swing.JRadioButton debitCardRadioButton;
    javax.swing.JList itemListJList;
    javax.swing.JTable itemListTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel netAmountLabel;
    javax.swing.JTextField netAmountTextField;
    private javax.swing.JPanel newInvoicePanel;
    javax.swing.JLabel noLabel;
    javax.swing.JTextField noTextField;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup paymentMethodButtonGroup;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JPanel paymentPanel;
    javax.swing.JCheckBox printCheckBox;
    private javax.swing.JLabel searchLabel;
    javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViewInternalFrameListener(InternalFrameListener ifl) {
        this.addInternalFrameListener(ifl);
    }

    public void addOKButtonActionListener(ActionListener al) {
        okButton.addActionListener(al);
    }

    public void addClearButtonActionListener(ActionListener al) {
        clearButton.addActionListener(al);
    }

    public void addCashRadioButtonActionListener(ActionListener al) {
        cashRadioButton.addActionListener(al);
    }

    public void addChequeRadioButtonActionListener(ActionListener al) {
        chequeRadioButton.addActionListener(al);
    }

    public void addDebitCardRadioButtonActionListener(ActionListener al) {
        debitCardRadioButton.addActionListener(al);
    }

    public void addCreditCardRadioButtonActionListener(ActionListener al) {
        creditCardRadioButton.addActionListener(al);
    }

    public void addItemListMouseListener(MouseListener ml) {
        itemListJList.addMouseListener(ml);
    }
    
    public void addSearchTextFieldActionListener(KeyListener kl){
        searchTextField.addKeyListener(kl);
    }
    
    public void addAmountPaidTextFieldActionListener(MouseListener ml){
        amountPaidTextField.addMouseListener(ml);
    }
}
