/*
 * Copyright © 02.10.2015 by O.I.Mudannayake. All Rights Reserved.
 */
package salesreturn;

import java.awt.event.ActionListener;
import javax.swing.event.InternalFrameListener;
import controller.View;
import javax.swing.BorderFactory;
import ui.ColourPalatte;

/**
 *
 * @author Ivantha
 */
public class NewSRN extends javax.swing.JInternalFrame implements View{

    /**
     * Creates new form NewPRNView
     */
    public NewSRN() {
        initComponents();
        
        this.newSRNPanel.setBackground(ColourPalatte.MEDIUM_BLUE);
        this.paymentPanel.setBackground(ColourPalatte.MEDIUM_BLUE);

        this.invoiceNoLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.descriptionLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.refundPaymentLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.paymentMethodLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.bankLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.noLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        
        this.refundPaymentTextField.setBackground(ColourPalatte.VERY_LIGHT_BLUE);
        this.descriptionTextArea.setBackground(ColourPalatte.PALE_WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentMethodButtonGroup = new javax.swing.ButtonGroup();
        newSRNPanel = new javax.swing.JPanel();
        invoiceNoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemListTable = new javax.swing.JTable();
        refundPaymentLabel = new javax.swing.JLabel();
        refundPaymentTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        paymentMethodLabel = new javax.swing.JLabel();
        cashRadioButton = new javax.swing.JRadioButton();
        chequeRadioButton = new javax.swing.JRadioButton();
        debitCardRadioButton = new javax.swing.JRadioButton();
        creditCardRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();
        bankTextField = new javax.swing.JTextField();
        noLabel = new javax.swing.JLabel();
        noTextField = new javax.swing.JTextField();
        bankLabel = new javax.swing.JLabel();
        printCheckBox = new javax.swing.JCheckBox();
        invoiceNoTextField = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Sales return note");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/icon/srn_button_dark.png"))); // NOI18N

        invoiceNoLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        invoiceNoLabel.setText("Invoice no.");

        itemListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item no.", "Name", "Qty", "Unit price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemListTable.setRowHeight(20);
        jScrollPane1.setViewportView(itemListTable);

        refundPaymentLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        refundPaymentLabel.setText("Refund payment");

        refundPaymentTextField.setEditable(false);
        refundPaymentTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        refundPaymentTextField.setText(" ");
        refundPaymentTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        descriptionLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        descriptionLabel.setText("Description");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        descriptionTextArea.setRows(5);
        descriptionTextArea.setBorder(null);
        jScrollPane2.setViewportView(descriptionTextArea);

        paymentMethodLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        paymentMethodLabel.setText("Payment method");

        paymentMethodButtonGroup.add(cashRadioButton);
        cashRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cashRadioButton.setText("Cash");

        paymentMethodButtonGroup.add(chequeRadioButton);
        chequeRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        chequeRadioButton.setText("Cheque");

        paymentMethodButtonGroup.add(debitCardRadioButton);
        debitCardRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        debitCardRadioButton.setText("Debit card");

        paymentMethodButtonGroup.add(creditCardRadioButton);
        creditCardRadioButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        creditCardRadioButton.setText("Credit card");

        okButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButtonMouseExited(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearButtonMouseExited(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addButtonMouseExited(evt);
            }
        });

        removeButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeButton.setText("Remove");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeButtonMouseExited(evt);
            }
        });

        paymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bankTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bankTextField.setText(" ");
        bankTextField.setBorder(null);
        paymentPanel.add(bankTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 25));

        noLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        noLabel.setText("No.");
        paymentPanel.add(noLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        noTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        noTextField.setText(" ");
        noTextField.setBorder(null);
        paymentPanel.add(noTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, 25));

        bankLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bankLabel.setText("Bank");
        paymentPanel.add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        printCheckBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        printCheckBox.setText("Print");
        printCheckBox.setPreferredSize(new java.awt.Dimension(80, 25));

        invoiceNoTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        invoiceNoTextField.setText(" ");
        invoiceNoTextField.setBorder(null);

        javax.swing.GroupLayout newSRNPanelLayout = new javax.swing.GroupLayout(newSRNPanel);
        newSRNPanel.setLayout(newSRNPanelLayout);
        newSRNPanelLayout.setHorizontalGroup(
            newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSRNPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newSRNPanelLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(newSRNPanelLayout.createSequentialGroup()
                        .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newSRNPanelLayout.createSequentialGroup()
                                .addComponent(invoiceNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(invoiceNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(newSRNPanelLayout.createSequentialGroup()
                                    .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(paymentMethodLabel)
                                        .addGroup(newSRNPanelLayout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(chequeRadioButton)
                                                .addComponent(cashRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(debitCardRadioButton)
                                                .addComponent(creditCardRadioButton))))
                                    .addGap(112, 112, 112)
                                    .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(newSRNPanelLayout.createSequentialGroup()
                                            .addComponent(refundPaymentLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(refundPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(50, 50, 50))
                                .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(newSRNPanelLayout.createSequentialGroup()
                                        .addComponent(printCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(newSRNPanelLayout.createSequentialGroup()
                                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        newSRNPanelLayout.setVerticalGroup(
            newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSRNPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNoLabel)
                    .addComponent(invoiceNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newSRNPanelLayout.createSequentialGroup()
                        .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refundPaymentLabel)
                            .addComponent(refundPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(newSRNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newSRNPanelLayout.createSequentialGroup()
                        .addComponent(paymentMethodLabel)
                        .addGap(6, 6, 6)
                        .addComponent(cashRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chequeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(debitCardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creditCardRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newSRNPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newSRNPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseEntered
        this.okButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.okButton.setForeground(ColourPalatte.FONT_BLUE);
        this.okButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_okButtonMouseEntered

    private void okButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseExited
        this.okButton.setBackground(ColourPalatte.DARK_BLUE);
        this.okButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.okButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_okButtonMouseExited

    private void clearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseEntered
        this.clearButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.clearButton.setForeground(ColourPalatte.FONT_BLUE);
        this.clearButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_clearButtonMouseEntered

    private void clearButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseExited
        this.clearButton.setBackground(ColourPalatte.DARK_BLUE);
        this.clearButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.clearButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_clearButtonMouseExited

    private void addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseEntered
        this.addButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.addButton.setForeground(ColourPalatte.FONT_BLUE);
        this.addButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_addButtonMouseEntered

    private void addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseExited
        this.addButton.setBackground(ColourPalatte.DARK_BLUE);
        this.addButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.addButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_addButtonMouseExited

    private void removeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseEntered
        this.removeButton.setBackground(ColourPalatte.VERY_DARK_BLUE);
        this.removeButton.setForeground(ColourPalatte.FONT_BLUE);
        this.removeButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.FONT_BLUE, 1));
    }//GEN-LAST:event_removeButtonMouseEntered

    private void removeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseExited
        this.removeButton.setBackground(ColourPalatte.DARK_BLUE);
        this.removeButton.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.removeButton.setBorder(BorderFactory.createLineBorder(ColourPalatte.BRIGHT_WHITE, 1));
    }//GEN-LAST:event_removeButtonMouseExited
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    javax.swing.JLabel bankLabel;
    javax.swing.JTextField bankTextField;
    javax.swing.JRadioButton cashRadioButton;
    javax.swing.JRadioButton chequeRadioButton;
    private javax.swing.JButton clearButton;
    javax.swing.JRadioButton creditCardRadioButton;
    javax.swing.JRadioButton debitCardRadioButton;
    private javax.swing.JLabel descriptionLabel;
    javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel invoiceNoLabel;
    javax.swing.JTextField invoiceNoTextField;
    javax.swing.JTable itemListTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel newSRNPanel;
    javax.swing.JLabel noLabel;
    javax.swing.JTextField noTextField;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup paymentMethodButtonGroup;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JPanel paymentPanel;
    javax.swing.JCheckBox printCheckBox;
    private javax.swing.JLabel refundPaymentLabel;
    javax.swing.JTextField refundPaymentTextField;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViewInternalFrameListener(InternalFrameListener ifl) {
        this.addInternalFrameListener(ifl);
    }
    
    public void addAddButtonActionListener(ActionListener al){
        addButton.addActionListener(al);
    }
    
    public void addRemoveButtonActionListener(ActionListener al){
        removeButton.addActionListener(al);
    }
    
    public void addOKButtonActionListener(ActionListener al){
        okButton.addActionListener(al);
    }
    
    public void addClearButtonActionListener(ActionListener al){
        clearButton.addActionListener(al);
    }
    
    public void addCashRadioButtonActionListener(ActionListener al){
        cashRadioButton.addActionListener(al);
    }
    
    public void addChequeRadioButtonActionListener(ActionListener al){
        chequeRadioButton.addActionListener(al);
    }
    
    public void addDebitCardRadioButtonActionListener(ActionListener al){
        debitCardRadioButton.addActionListener(al);
    }
    
    public void addCreditCardRadioButtonActionListener(ActionListener al){
        creditCardRadioButton.addActionListener(al);
    }
}
