/*
 * Copyright © 02.10.2015 by O.I.Mudannayake. All Rights Reserved.
 */
package management.supplier;

import javax.swing.event.InternalFrameListener;
import controller.View;
import ui.ColourPalatte;

/**
 *
 * @author Ivantha
 */
public class SupplierHistory extends javax.swing.JInternalFrame implements View{

    /**
     * Creates new form SupplierHistoryView
     */
    public SupplierHistory() {
        initComponents();
        
        this.supplierHistoryPanel.setBackground(ColourPalatte.MEDIUM_BLUE);
        this.supplierDetailPanel.setBackground(ColourPalatte.DARK_BLUE);
        
        this.supplierIDLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.supplierIDTextField.setBackground(ColourPalatte.VERY_LIGHT_BLUE);
        this.nameLabel.setForeground(ColourPalatte.BRIGHT_WHITE);
        this.nameTextField.setBackground(ColourPalatte.VERY_LIGHT_BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supplierHistoryPanel = new javax.swing.JPanel();
        supplierDetailPanel = new javax.swing.JPanel();
        supplierIDLabel = new javax.swing.JLabel();
        supplierIDTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        supplierHistoryTable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Supplier history");

        supplierIDLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        supplierIDLabel.setText("Supplier ID");

        supplierIDTextField.setEditable(false);
        supplierIDTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        supplierIDTextField.setText(" ");
        supplierIDTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nameLabel.setText("Name");

        nameTextField.setEditable(false);
        nameTextField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nameTextField.setText(" ");
        nameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout supplierDetailPanelLayout = new javax.swing.GroupLayout(supplierDetailPanel);
        supplierDetailPanel.setLayout(supplierDetailPanelLayout);
        supplierDetailPanelLayout.setHorizontalGroup(
            supplierDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierDetailPanelLayout.createSequentialGroup()
                .addComponent(supplierIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        supplierDetailPanelLayout.setVerticalGroup(
            supplierDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierDetailPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(supplierDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierIDLabel)
                    .addComponent(supplierIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        supplierHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PO", "PO date", "PRN no.", "Employee name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplierHistoryTable.setRowHeight(20);
        jScrollPane1.setViewportView(supplierHistoryTable);
        if (supplierHistoryTable.getColumnModel().getColumnCount() > 0) {
            supplierHistoryTable.getColumnModel().getColumn(0).setMinWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(0).setMaxWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(1).setMinWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(1).setMaxWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(2).setMinWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            supplierHistoryTable.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout supplierHistoryPanelLayout = new javax.swing.GroupLayout(supplierHistoryPanel);
        supplierHistoryPanel.setLayout(supplierHistoryPanelLayout);
        supplierHistoryPanelLayout.setHorizontalGroup(
            supplierHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierHistoryPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(supplierHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplierDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(25, 25, 25))
        );
        supplierHistoryPanelLayout.setVerticalGroup(
            supplierHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierHistoryPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(supplierDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supplierHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supplierHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    javax.swing.JTextField nameTextField;
    private javax.swing.JPanel supplierDetailPanel;
    private javax.swing.JPanel supplierHistoryPanel;
    javax.swing.JTable supplierHistoryTable;
    private javax.swing.JLabel supplierIDLabel;
    javax.swing.JTextField supplierIDTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateViewInternalFrameListener(InternalFrameListener ifl) {
        this.addInternalFrameListener(ifl);
    }
}
